packages: []
strictPeerDependencies: true
engineStrict: true
allowBuilds:
  esbuild: true
  '@conceptadev/docs-theme@git+ssh://git@github.com/conceptadev/docs-theme.git#75c0bc67a2b075b8d64da7daa206e9f341d00c84': true
minimumReleaseAgeStrict: true
minimumReleaseAgeExclude:
  - '@fumadocs/base-ui@16.15.8'
  - 'fumadocs-core@16.15.8'
