import 'dart:convert';
import 'dart:io';

/// Renders `docs/fortal/catalog.mdx` from the pinned Radix Themes parity
/// manifest.
///
/// The manifest is already the catalog: it records every family's enums,
/// defaults, style props, states, and parity boundaries, and
/// `melos fortal:parity:check` holds each of those against the Dart recipes.
/// Writing the page by hand would fork a second source of truth that nothing
/// checks, so this renders the one that is already enforced.
///
/// Pass `--check` to fail on drift instead of writing, which is how
/// `melos docs:check` runs it.
void main(List<String> arguments) {
  final check = arguments.contains('--check');
  final unknown = arguments.where((argument) => argument != '--check');
  if (unknown.isNotEmpty) {
    stderr.writeln('Unsupported arguments: ${unknown.join(', ')}');
    exitCode = 64;
    return;
  }

  final workspaceRoot = Directory.current;
  final pubspec = File('${workspaceRoot.path}/pubspec.yaml');
  if (!pubspec.existsSync() ||
      !RegExp(
        r'^name:\s*remix_workspace\s*$',
        multiLine: true,
      ).hasMatch(pubspec.readAsStringSync())) {
    stderr.writeln('Run this generator from the workspace root.');
    exitCode = 64;
    return;
  }

  final packageRoot = Directory('${workspaceRoot.path}/packages/remix_fortal');
  final manifestFile = File(
    '${packageRoot.path}/reference/radix_themes_3_3_0/manifest.json',
  );
  if (!manifestFile.existsSync()) {
    stderr.writeln('Missing ${manifestFile.path}.');
    exitCode = 1;
    return;
  }

  final manifest =
      jsonDecode(manifestFile.readAsStringSync()) as Map<String, Object?>;
  final rendered = _render(manifest, packageRoot);
  final output = File('${workspaceRoot.path}/docs/fortal/catalog.mdx');

  if (!check) {
    output.parent.createSync(recursive: true);
    output.writeAsStringSync(rendered);
    stdout.writeln('Wrote docs/fortal/catalog.mdx.');
    return;
  }

  if (!output.existsSync()) {
    stderr.writeln(
      'docs/fortal/catalog.mdx is missing. Run `melos docs:catalog`.',
    );
    exitCode = 1;
    return;
  }
  if (output.readAsStringSync() != rendered) {
    stderr.writeln(
      'docs/fortal/catalog.mdx is stale. Run `melos docs:catalog` and commit '
      'the result.',
    );
    exitCode = 1;
    return;
  }
  stdout.writeln('docs/fortal/catalog.mdx matches the parity manifest.');
}

String _render(Map<String, Object?> manifest, Directory packageRoot) {
  final families =
      (manifest['families']! as List<Object?>)
          .cast<Map<String, Object?>>()
          .toList()
        ..sort(
          (left, right) => (left['fortalType']! as String).compareTo(
            right['fortalType']! as String,
          ),
        );
  final source = (manifest['source']! as Map<String, Object?>);
  final version = source['version'] as String;

  final buffer = StringBuffer()
    ..writeln('---')
    ..writeln('title: Catalog')
    ..writeln(
      'description: Every Fortal widget with its sizes, variants, defaults, '
      'and parity boundaries',
    )
    ..writeln('---')
    ..writeln()
    ..writeln(
      '{/* Generated by tool/generate_fortal_catalog.dart from the pinned '
      'Radix Themes $version parity manifest. Do not edit by hand: run '
      '`melos docs:catalog`. `melos docs:check` fails on drift. */}',
    )
    ..writeln()
    ..writeln(
      'Every widget below is generated from the parity manifest that '
      '`melos fortal:parity:check` holds against the Dart recipes, so the '
      'sizes, variants, and defaults on this page are the ones a caller '
      'actually gets.',
    )
    ..writeln()
    ..writeln('<Card>')
    ..writeln(
      '  <img src="/assets/fortal-catalog.png" alt="Fortal components across '
      'their variants" />',
    )
    ..writeln('</Card>')
    ..writeln()
    ..writeln(
      'A `—` default means the parameter is nullable with no pinned value. '
      'That is the typography path: an omitted size or weight resolves from '
      'the active scope\'s tokens (`text3`, regular) rather than from an '
      'enum, so a host text run cannot resize Fortal text. See '
      '[Typography](/fortal/typography).',
    )
    ..writeln();

  _writeGlanceTable(buffer, families, packageRoot);
  _writeFamilySections(buffer, families, manifest, packageRoot);
  _writeUnmapped(buffer, manifest);

  return buffer.toString();
}

void _writeGlanceTable(
  StringBuffer buffer,
  List<Map<String, Object?>> families,
  Directory packageRoot,
) {
  buffer
    ..writeln('## At a glance')
    ..writeln()
    ..writeln('| Widget | Sizes | Size default | Variants | Variant default |')
    ..writeln('| --- | --- | --- | --- | --- |');
  for (final family in families) {
    final enums = (family['enums'] as Map<String, Object?>?) ?? const {};
    final carriers = _parameterCarriers(packageRoot, family, enums);
    final size = enums['size'] as Map<String, Object?>?;
    final variant = enums['variant'] as Map<String, Object?>?;
    buffer.writeln(
      '| `${family['fortalType']}` '
      '| ${_valueList(size)} | ${_defaultCell(size, carriers['size'])} '
      '| ${_valueList(variant)} '
      '| ${_defaultCell(variant, carriers['variant'])} |',
    );
  }
  buffer.writeln();
}

void _writeFamilySections(
  StringBuffer buffer,
  List<Map<String, Object?>> families,
  Map<String, Object?> manifest,
  Directory packageRoot,
) {
  final approximations = (manifest['approximations']! as List<Object?>)
      .cast<Map<String, Object?>>();

  buffer
    ..writeln('## Widgets')
    ..writeln();

  for (final family in families) {
    final id = family['id']! as String;
    final fortalType = family['fortalType']! as String;
    final enums = (family['enums'] as Map<String, Object?>?) ?? const {};
    final recipePath = _recipePath(id);

    buffer
      ..writeln('### $fortalType')
      ..writeln();

    final radix = family['radixComponent'];
    final origin = radix is String
        ? 'Radix `$radix`'
        : 'Fortal extension (no Radix counterpart)';
    buffer
      ..writeln('$origin · recipe `packages/remix_fortal/$recipePath`')
      ..writeln();

    if (enums.isNotEmpty) {
      final carriers = _parameterCarriers(packageRoot, family, enums);
      buffer
        ..writeln('| Parameter | Values | Default |')
        ..writeln('| --- | --- | --- |');
      final kinds = enums.keys.toList()..sort();
      for (final kind in kinds) {
        final definition = enums[kind]! as Map<String, Object?>;
        buffer.writeln(
          '| `$kind` | ${_valueList(definition)} '
          '| ${_defaultCell(definition, carriers[kind])} |',
        );
      }
      buffer.writeln();
    }

    final constructors = _namedConstructors(packageRoot, id, fortalType);
    if (constructors.isNotEmpty) {
      final rendered = constructors
          .map((name) => '`$fortalType.$name`')
          .join(', ');
      buffer
        ..writeln('**Named constructors:** $rendered')
        ..writeln();
    }

    final otherDefaults = _otherDefaults(family, enums);
    if (otherDefaults.isNotEmpty) {
      buffer
        ..writeln('**Other defaults:** $otherDefaults')
        ..writeln();
    }

    _writeInlineList(buffer, 'Style props', family['supportedStyleProps']);
    _writeInlineList(buffer, 'States', family['states']);
    _writeBulletList(
      buffer,
      'Flutter differences',
      family['flutterExceptions'],
    );
    _writeBulletList(buffer, 'Not covered', family['deferredCapabilities']);

    final familyApproximations = approximations
        .where((entry) => entry['family'] == id)
        .toList();
    if (familyApproximations.isNotEmpty) {
      buffer
        ..writeln('**Documented approximations:**')
        ..writeln();
      for (final entry in familyApproximations) {
        buffer.writeln('- ${_escape(entry['reason']! as String)}');
      }
      buffer.writeln();
    }
  }
}

void _writeUnmapped(StringBuffer buffer, Map<String, Object?> manifest) {
  final unmapped = (manifest['unmappedUpstreamFamilies']! as List<Object?>)
      .cast<Map<String, Object?>>();
  if (unmapped.isEmpty) return;

  buffer
    ..writeln('## Audited, not mapped')
    ..writeln()
    ..writeln(
      'These upstream families are tracked deliberately rather than missed. '
      'Each names the Remix composition that covers it today and the '
      'condition that would reopen it.',
    )
    ..writeln();

  for (final family in unmapped) {
    buffer
      ..writeln('### Radix `${family['radixComponent']}`')
      ..writeln()
      ..writeln('- **Why not mapped:** ${_escape(family['reason']! as String)}')
      ..writeln(
        '- **Use instead:** '
        '${_escape(family['supportedRemixComposition']! as String)}',
      )
      ..writeln(
        '- **Reopens when:** ${_escape(family['reopenCondition']! as String)}',
      )
      ..writeln();
  }
}

/// The named constructors [fortalType] actually declares.
///
/// Read from source rather than derived from the variant values: the variant
/// set and the constructor set are held equal by `_checkVariantConstructors`
/// in the parity checker, so reading either would give the same answer, but
/// reading the source also reports the hand-written widgets (`FortalCode`,
/// `FortalKbd`) that no generator emits.
List<String> _namedConstructors(
  Directory packageRoot,
  String id,
  String fortalType,
) {
  final recipe = File('${packageRoot.path}/${_recipePath(id)}');
  if (!recipe.existsSync()) return const [];
  final generated = File(
    recipe.path.replaceFirst(RegExp(r'\.dart$'), '.g.dart'),
  );
  final source =
      '${recipe.readAsStringSync()}\n'
      '${generated.existsSync() ? generated.readAsStringSync() : ''}';

  final names = RegExp(
    'const\\s+${RegExp.escape(fortalType)}\\.([A-Za-z0-9_]+)\\s*\\(',
  ).allMatches(source).map((match) => match.group(1)!).toSet().toList()..sort();
  return names;
}

/// TextField and TextArea share one recipe file because TextArea reuses
/// TextField's private helpers; this mirrors the same mapping the parity
/// checker uses so both name the identical source.
String _recipePath(String id) {
  final recipeName = switch (id) {
    'text_field' || 'text_area' => 'textfield',
    _ => id,
  };
  return 'lib/src/recipes/$recipeName.dart';
}

String _otherDefaults(Map<String, Object?> family, Map<String, Object?> enums) {
  final defaults = (family['defaults'] as Map<String, Object?>?) ?? const {};
  final keys = defaults.keys.where((key) => !enums.containsKey(key)).toList()
    ..sort();
  return keys.map((key) => '`$key: ${defaults[key]}`').join(', ');
}

void _writeInlineList(StringBuffer buffer, String label, Object? value) {
  if (value is! List<Object?> || value.isEmpty) return;
  final rendered = value.cast<String>().map((item) => '`$item`').join(', ');
  buffer
    ..writeln('**$label:** $rendered')
    ..writeln();
}

void _writeBulletList(StringBuffer buffer, String label, Object? value) {
  if (value is! List<Object?> || value.isEmpty) return;
  buffer
    ..writeln('**$label:**')
    ..writeln();
  for (final item in value.cast<String>()) {
    buffer.writeln('- ${_escape(item)}');
  }
  buffer.writeln();
}

String _valueList(Map<String, Object?>? definition) {
  if (definition == null) return '—';
  final values = (definition['values'] as List<Object?>? ?? const [])
      .cast<String>();
  if (values.isEmpty) return '—';
  return values.map((value) => '`$value`').join(', ');
}

String _defaultCell(Map<String, Object?>? definition, [String? carrier]) {
  if (definition == null) return '—';
  final value = definition['default'];
  final rendered = value == null ? '—' : '`$value`';
  return carrier == null ? rendered : '$rendered (on `$carrier`)';
}

/// The widget each enum parameter is actually declared on, but only where that
/// differs from the family's root type.
///
/// A family is one manifest entry and can publish several widgets. Tabs is the
/// case in point: Radix takes `size` on `Tabs.List`, but the Fortal tab-list
/// border is one hairline at every size, so the recipe moves `size` onto
/// `FortalTab` where the metrics actually vary. Reading the declaration keeps
/// the page from claiming `FortalTabBar(size: ...)` compiles.
Map<String, String> _parameterCarriers(
  Directory packageRoot,
  Map<String, Object?> family,
  Map<String, Object?> enums,
) {
  final fortalType = family['fortalType']! as String;
  final recipe = File(
    '${packageRoot.path}/${_recipePath(family['id']! as String)}',
  );
  if (!recipe.existsSync()) return const {};
  final generated = File(
    recipe.path.replaceFirst(RegExp(r'\.dart$'), '.g.dart'),
  );
  final source =
      '${recipe.readAsStringSync()}\n'
      '${generated.existsSync() ? generated.readAsStringSync() : ''}';

  final bodies = _classBodies(source);
  final carriers = <String, String>{};
  for (final kind in enums.keys) {
    final declares = RegExp('this\\.$kind\\b');
    if (declares.hasMatch(bodies[fortalType] ?? '')) continue;
    final owners =
        bodies.entries
            .where((entry) => declares.hasMatch(entry.value))
            .map((entry) => entry.key)
            .toList()
          ..sort();
    if (owners.length == 1) carriers[kind] = owners.single;
  }
  return carriers;
}

/// Class name to source body, each body running to the next top-level class.
///
/// Good enough because Fortal widgets are flat top-level classes; it never has
/// to survive a nested or generic declaration.
Map<String, String> _classBodies(String source) {
  final matches = RegExp(
    r'^class\s+([A-Za-z0-9_]+)',
    multiLine: true,
  ).allMatches(source).toList();
  final bodies = <String, String>{};
  for (final (index, match) in matches.indexed) {
    final end = index + 1 < matches.length
        ? matches[index + 1].start
        : source.length;
    bodies[match.group(1)!] = source.substring(match.end, end);
  }
  return bodies;
}

/// Table cells and list items carry manifest prose verbatim, so anything that
/// would be read as Markdown structure has to be neutralised first.
String _escape(String value) => value.replaceAll('|', r'\|');
